# Generated by Django 5.0.6 on 2024-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
