# Generated by Django 5.0.6 on 2024-07-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('image', models.URLField(blank=True, verbose_name='Фото')),
                ('release_date', models.DateField(blank=True, verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='В наличии')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
